import { describe, it, expect } from "vitest";
import { getValidator, type ModuleSubtype } from "@/validators";
import { CURRENT_SCHEMA_VERSION } from "@/manager/import-export/migrations";

// Fixtures generated by `scripts/dump_engine_shapes.py` -- one real,
// engine-handler-validated payload per module subtype. See that script
// for the why: it makes the engine the single source of truth so the
// community TS validators can't silently drift from it (the
// fixed_values entries-vs-values class of bug).
import wildcardRow from "@/validators/fixtures/engine-parity/wildcard.json";
import fixedValuesRow from "@/validators/fixtures/engine-parity/fixed_values.json";
import combineRow from "@/validators/fixtures/engine-parity/combine.json";
import derivationRow from "@/validators/fixtures/engine-parity/derivation.json";
import constraintRow from "@/validators/fixtures/engine-parity/constraint.json";

const ROWS: { subtype: ModuleSubtype; row: unknown }[] = [
  { subtype: "wildcard", row: wildcardRow },
  { subtype: "fixed_values", row: fixedValuesRow },
  { subtype: "combine", row: combineRow },
  { subtype: "derivation", row: derivationRow },
  { subtype: "constraint", row: constraintRow },
];

describe("engine parity: strict v1 validators accept real engine output", () => {
  for (const { subtype, row } of ROWS) {
    it(`strict ${subtype} validator accepts the engine-dumped row`, () => {
      const validator = getValidator({
        kind: "module",
        subtype,
        version: CURRENT_SCHEMA_VERSION,
        mode: "strict",
      });
      const result = validator.safeParse(row);
      // On failure, surface the Zod issues so the diff between the
      // engine shape and the validator is obvious -- this is the
      // message a future contributor sees when they drift one side.
      expect(
        result.success,
        result.success ? "" : JSON.stringify(result.error.issues, null, 2),
      ).toBe(true);
    });
  }
});

// Acceptance isn't enough: the lenient payload object silently strips any key
// the schema doesn't list, and install stores the parsed row — so an unlisted
// field is lost even though validation "passed". These lock that the tag-axes
// kind map and the constraint reach selector are actually PRESERVED, which is
// the whole point of listing them (a shared accepts axis must not degrade to
// classify on import).
describe("engine parity: strict parse preserves tag-axes + reach fields", () => {
  it("wildcard keeps tag_group_kinds through a strict parse", () => {
    const validator = getValidator({
      kind: "module",
      subtype: "wildcard",
      version: CURRENT_SCHEMA_VERSION,
      mode: "strict",
    });
    const parsed = validator.parse(wildcardRow) as {
      payload: { tag_group_kinds?: unknown };
    };
    expect(parsed.payload.tag_group_kinds).toEqual({ TEXTURE: "accepts" });
  });

  it("constraint keeps target_select through a strict parse", () => {
    const validator = getValidator({
      kind: "module",
      subtype: "constraint",
      version: CURRENT_SCHEMA_VERSION,
      mode: "strict",
    });
    const parsed = validator.parse(constraintRow) as {
      payload: { target_select?: unknown };
    };
    expect(parsed.payload.target_select).toEqual({ mode: "next", count: 2 });
  });
});
