"""Booru tag index for the optional value autocomplete.

Pure Python — no aiohttp, no ComfyUI — so the parsing and search behaviour is
testable on its own. `wp_api/tags.py` wraps it in routes.

WHY A FILE AND NOT A BUNDLE. A usable tag list is 2-6 MB; the extension's whole
gzipped JS budget is 420 KB. It cannot ship in the package, and it must not be
sent to the browser either — searching happens here and the client receives ~20
rows per keystroke.

WHY OUR OWN PATH ONLY. Several other extensions keep tag files
(`ComfyUI-Custom-Scripts`, `ComfyUI-LoRA-Manager`), and reading theirs directly
would couple us to layouts they are free to change. Instead the list is
generated by our own CI workflow and downloaded into a path we own. One source,
no scavenging.

FORMAT. Comma-separated, one tag per line, in the shape the ecosystem already
uses:

    name,post_count
    name,category,post_count,"alias,alias"

Both are accepted — the first is the `ComfyUI-Custom-Scripts` shape, the second
carries the category the Danbooru API returns (0 general, 1 artist,
3 copyright, 4 character, 5 meta). A file in the first shape simply has no
categories and the UI degrades to plain rows.
"""
from __future__ import annotations

import csv
import logging
from bisect import bisect_left
from dataclasses import dataclass
from pathlib import Path

_log = logging.getLogger(__name__)

#: Danbooru's numeric categories. Anything else is surfaced as-is.
CATEGORY_NAMES = {
    0: "general",
    1: "artist",
    3: "copyright",
    4: "character",
    5: "meta",
}

#: Guard against pointing this at something enormous by accident. A full
#: Danbooru dump above the post-count floor is ~250k rows; ten times that is
#: not a tag list, it is a mistake, and loading it would stall the request.
_MAX_ROWS = 2_000_000


@dataclass(frozen=True, slots=True)
class Tag:
    name: str
    count: int
    category: int | None
    #: The tag this one redirects to, when the row came from an alias column.
    aliased_to: str | None = None


def _parse_row(row: list[str]) -> Tag | None:
    """One CSV row -> Tag, or None when the row is not usable.

    Distinguishing the two layouts comes down to where the big number is:
    `name,count` has it in column 1, `name,category,count,aliases` in column 2.
    Category is a small enum and post counts are large, so "the second column
    is a plausible category and a third column parses as an int" is a reliable
    tell without needing a header.
    """
    if not row:
        return None
    name = row[0].strip()
    if not name or name.startswith("#"):
        return None
    try:
        if len(row) >= 3 and row[1].strip().isdigit() and row[2].strip().isdigit():
            category = int(row[1])
            count = int(row[2])
            # A category is a small enum; a post count is not. If column 1 is
            # large it is a count and this is a two-column file with extra
            # junk, not a four-column one.
            if category > 20:
                return Tag(name=name, count=category, category=None)
            return Tag(name=name, count=count, category=category)
        if len(row) >= 2 and row[1].strip().isdigit():
            return Tag(name=name, count=int(row[1]), category=None)
    except ValueError:
        return None
    return None


def _aliases_from_row(row: list[str]) -> list[str]:
    """Alias names in the 4th column, if the file carries them."""
    if len(row) < 4:
        return []
    raw = row[3].strip().strip('"')
    if not raw:
        return []
    return [a.strip() for a in raw.split(",") if a.strip()]


class TagIndex:
    """A searchable snapshot of one tag file.

    Built once and reused. `is_stale` lets the caller rebuild when the file
    changes underneath it without watching the filesystem.
    """

    def __init__(self, path: Path, tags: list[Tag], mtime: float) -> None:
        self.path = path
        self._mtime = mtime
        #: Sorted by name so a prefix query is a bisect rather than a scan of
        #: a quarter of a million rows on every keystroke.
        self._tags = sorted(tags, key=lambda t: t.name)
        self._names = [t.name for t in self._tags]

    def __len__(self) -> int:
        return len(self._tags)

    @property
    def has_categories(self) -> bool:
        return any(t.category is not None for t in self._tags)

    def is_stale(self) -> bool:
        try:
            return self.path.stat().st_mtime != self._mtime
        except OSError:
            return True

    def search(self, query: str, limit: int = 20) -> list[Tag]:
        """Tags starting with `query`, most-used first.

        Prefix only, deliberately. Substring matching over 200k tags returns
        pages of noise for a two-letter query and buries the tag actually
        wanted; every booru autocomplete users already know behaves this way.
        Aliases are indexed as their own entries, so `hires` still finds
        `highres` without needing a substring pass.
        """
        q = query.strip().lower().replace(" ", "_")
        if not q:
            return []
        start = bisect_left(self._names, q)
        # Deduplicated by the tag that would actually be inserted. A canonical
        # tag and its aliases are separate entries, so `1girl` matched both
        # `1girl` and the alias `1girls` and rendered the same row twice.
        # A direct hit beats an alias hit for the same canonical: `1girl`
        # should be listed as itself, not as "1girls -> 1girl".
        best: dict[str, Tag] = {}
        scanned = 0
        for i in range(start, len(self._names)):
            if not self._names[i].startswith(q):
                break
            tag = self._tags[i]
            canonical = tag.aliased_to or tag.name
            incumbent = best.get(canonical)
            if incumbent is None or (
                incumbent.aliased_to is not None and tag.aliased_to is None
            ):
                best[canonical] = tag
            scanned += 1
            # Bounded so a single-letter query cannot walk half the file.
            if scanned >= 2000:
                break
        hits = sorted(best.values(), key=lambda t: -t.count)
        return hits[:limit]


def load_index(path: Path) -> TagIndex | None:
    """Read a tag file into an index, or None if it cannot be used.

    Never raises. A missing or malformed file means the feature is simply
    unavailable — it is optional, and a broken tag list must not take an
    editor down with it.
    """
    try:
        stat = path.stat()
    except OSError:
        return None
    tags: list[Tag] = []
    seen: set[str] = set()
    try:
        with path.open("r", encoding="utf-8", newline="") as fh:
            for row in csv.reader(fh):
                if len(tags) >= _MAX_ROWS:
                    _log.warning(
                        "wildcard-pipeline: tag file %s exceeds %d rows; truncating",
                        path, _MAX_ROWS,
                    )
                    break
                tag = _parse_row(row)
                if tag is None or tag.name in seen:
                    continue
                seen.add(tag.name)
                tags.append(tag)
                for alias in _aliases_from_row(row):
                    if alias in seen:
                        continue
                    seen.add(alias)
                    # Aliases inherit the canonical tag's count so they rank
                    # where a user expects, and carry the redirect so the UI
                    # can insert the canonical name rather than the alias.
                    tags.append(
                        Tag(alias, tag.count, tag.category, aliased_to=tag.name),
                    )
    except (OSError, csv.Error, UnicodeDecodeError):
        _log.exception("wildcard-pipeline: failed reading tag file %s", path)
        return None
    if not tags:
        return None
    return TagIndex(path, tags, stat.st_mtime)
